---
logstash:
  url: 'https://download.elasticsearch.org/logstash/logstash' #'http://logstash.objects.dreamhost.com/release'
  jar: 'logstash-1.3.2-flatjar.jar' #monolithic.jar'
  dir: '/opt/logstash'
  conf: '/opt/logstash/etc'
  indexer: 
    conf: '/opt/logstash/etc/indexer.conf'
    service: 'logstash-indexer'
    name: 'logstash-indexer'

tmp_dir: '/tmp'

